print('első feladat ')
print('Szizáltáblák és softpályák, ')
print('jól megférnek egymás mellett. ')
print('Lelkes dartsosokat várják ')
print('jól felszerelt edzőtermek. ')

print('második feladat')
nev = input('hogyhivnak')
születésnap = input('Mikor születél ') 
születésihely = input('Holszületél ')
lakcim = input('Holélsz')

print('harmadik feladat')
x = int(input('adj meg egy számot '))
y = int(input('adj meg még egy számot '))
print( y,x )
print( x,y )

print('negyedik feladat')
a = int(input(' adj meg egy számot '))
b = int(input(' adj meg egy másik számot '))
print('A téglalap Területe t' ,a*b)
print('A Téglalap Kerülete' ,2*(a+b))

print('ötödik feladat')
a = int(input(' adj meg egy számot '))
b = int(input(' adj meg egy másik  számot '))
c = int(input(' adj meg még egy számot '))
print('A Háromszög Területe ' ,a*b/2 )
print('A Háromszög kerülete ' ,a+b+c )
